version: "3.7"

services:
  tcaudio:
    image: impacteai/transcrevezap:latest
    build: .
    networks:
      - suarededocker
    ports:
      - 8005:8005  # FastAPI
      - 8501:8501  # Streamlit
    environment:
      Uvicorn_port: 8005
      Uvicorn_host: 0.0.0.0
      Uvicorn_reload: "true"
      Uvicorn_workers: 1
      GROQ_API_KEY: "${GROQ_API_KEY}"
      BUSINESS_MESSAGE: "*Impacte AI* Premium Services"
      PROCESS_GROUP_MESSAGES: "false"
      PROCESS_SELF_MESSAGES: "true"
      DEBUG_MODE: "false"
      LOG_LEVEL: "INFO"
      MANAGER_USER: "admin"
      MANAGER_PASSWORD: "impacte2024"
    volumes:
      - ./config.json:/app/config.json
      - ./backups:/app/backups
      - ./transcription_logs.json:/app/transcription_logs.json
      - ./static:/app/static
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.tcaudio.rule=Host(`transcrevezap.seudominio.com.br`)
        - traefik.http.routers.tcaudio.entrypoints=websecure
        - traefik.http.routers.tcaudio.tls.certresolver=letsencryptresolver
        - traefik.http.services.tcaudio.loadbalancer.server.port=8005
        - traefik.http.services.tcaudio.loadbalancer.passHostHeader=true
        - traefik.http.routers.tcaudio.service=tcaudio
        - traefik.http.middlewares.traefik-compress.compress=true
        - traefik.http.routers.tcaudio.middlewares=traefik-compress
        # Configuração do Streamlit
        - traefik.http.routers.tcaudio-manager.rule=Host(`manager.transcrevezap.seudominio.com.br`)
        - traefik.http.routers.tcaudio-manager.entrypoints=websecure
        - traefik.http.routers.tcaudio-manager.tls.certresolver=letsencryptresolver
        - traefik.http.services.tcaudio-manager.loadbalancer.server.port=8501
        - traefik.http.routers.tcaudio-manager.service=tcaudio-manager

networks:
  suarededocker:
    external: true
    name: suarededocker
